# Generated by Django 4.0 on 2021-12-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_id', models.CharField(max_length=32)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('timezone', models.CharField(max_length=64)),
                ('timestamp', models.BigIntegerField()),
                ('temperature', models.IntegerField()),
                ('country', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('street', models.CharField(max_length=64)),
                ('altitude', models.IntegerField()),
            ],
        ),
    ]
