# Generated by Django 4.0 on 2021-12-21 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_measurement_source'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='measurement',
            unique_together={('measurement_id', 'timestamp')},
        ),
    ]
