# Generated by Django 4.0 on 2021-12-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0004_alter_measurement_temperature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='measurement_id',
            new_name='station_id',
        ),
        migrations.AlterUniqueTogether(
            name='measurement',
            unique_together={('station_id', 'timestamp')},
        ),
    ]
